import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Snap Basket",
  description: "Generated by create next app",
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      Common Navbar
      {children}
    </div>
  );
}
