import type { Metadata } from "next";
import Navbar from "./components/Shaared/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Snap Basket",
  description: "Generated by create next app",
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar></Navbar>
      {children}
    </div>
  );
}
